apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: room-6-backend-app
  app.kubernetes.io/instance: room-6-backend-app-instance
  app.kubernetes.io/name: room-6-backend-app
